name: Auto Update v2rayfree

on:
  schedule:
    - cron: '0 2,12 * * *'
  workflow_dispatch: 

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Update timestamp and content
      run: |
        sed -i "2s/.*/更新时间：$(date +%Y-%m-%d)/" v2rayfree
        head -n 2 v2rayfree > tempfile
        curl -s https://raw.githubusercontent.com/aiboboxx/v2rayfree/main/v2 >> tempfile
        mv tempfile v2rayfree

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add v2rayfree
        git commit -m "自动更新: $(date +'%Y-%m-%d %H:%M')"
        git push
